twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/public/styles/': css
        '%kernel.project_dir%/public/img/': images

when@test:
    twig:
        strict_variables: true
